// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8CMOe0pCMfGSZqML5Srmm48zbKX4LiCk',
    appId: '1:609438644219:android:9e3e707ac7cec6d8f47d5e',
    messagingSenderId: '609438644219',
    projectId: 'evently-a2274',
    storageBucket: 'evently-a2274.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZdwp340RL_8vLBiuTe1mSj39IH2_fuo8',
    appId: '1:609438644219:ios:6a78b0d803e8bea9f47d5e',
    messagingSenderId: '609438644219',
    projectId: 'evently-a2274',
    storageBucket: 'evently-a2274.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16Online',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClaHkgeBNEIAgQkhPaJ-YrRAiI_Rzrl38',
    appId: '1:609438644219:web:d13a7a8bc6aeac46f47d5e',
    messagingSenderId: '609438644219',
    projectId: 'evently-a2274',
    authDomain: 'evently-a2274.firebaseapp.com',
    storageBucket: 'evently-a2274.firebasestorage.app',
    measurementId: 'G-6H9MN60339',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZdwp340RL_8vLBiuTe1mSj39IH2_fuo8',
    appId: '1:609438644219:ios:9c9a737d6ec8da97f47d5e',
    messagingSenderId: '609438644219',
    projectId: 'evently-a2274',
    storageBucket: 'evently-a2274.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClaHkgeBNEIAgQkhPaJ-YrRAiI_Rzrl38',
    appId: '1:609438644219:web:d15c90295c7635e2f47d5e',
    messagingSenderId: '609438644219',
    projectId: 'evently-a2274',
    authDomain: 'evently-a2274.firebaseapp.com',
    storageBucket: 'evently-a2274.firebasestorage.app',
    measurementId: 'G-F1663X9EMM',
  );
}
